### ISSUE TITLE
Error after install and import the module

### ISSUE THREAD

**Issue by pookdeveloper** [rsaenen/ngx-custom-validators#45]
**IMPORTANT:**
ERROR in Symbol ArrayLengthValidator declared in C:/Users/HP/Desktop/shop/shop-fwk-front-core/node_modules/ngx-custom-validators/src/app/array-length/directive.d.ts is not exported from ngx-custom-validators/src/app/custom-forms.module (import into C:/Users/HP/Desktop/shop/shop-fwk-front-core/projects/merca-core-test/src/app/pages/error/error.component.ts)
C:\Users\HP\Desktop\shop\shop-fwk-front-core\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:456
                finally { if (e_7) throw e_7.error; }
                                   ^

Error: Symbol ArrayLengthValidator declared in C:/Users/HP/Desktop/shop/shop-fwk-front-core/node_modules/ngx-custom-validators/src/app/array-length/directive.d.ts is not exported from ngx-custom-validators/src/app/custom-forms.module (import into C:/Users/HP/Desktop/shop/shop-fwk-front-core/projects/merca-core-test/src/app/pages/error/error.component.ts)
    at AbsoluteModuleStrategy.emit (C:\Users\HP\Desktop\shop\shop-fwk-front-core\node_modules\@angular\compiler-cli\src\ngtsc\imports\src\emitter.js:156:23)
    at ReferenceEmitter.emit (C:\Users\HP\Desktop\shop\shop-fwk-front-core\node_modules\@angular\compiler-cli\src\ngtsc\imports\src\emitter.js:71:44)
    at ComponentDecoratorHandler.resolve (C:\Users\HP\Desktop\shop\shop-fwk-front-core\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\component.js:424:62)
    at TraitCompiler.resolve (C:\Users\HP\Desktop\shop\shop-fwk-front-core\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:398:50)
    at NgCompiler.resolveCompilation (C:\Users\HP\Desktop\shop\shop-fwk-front-core\node_modules\@angular\compiler-cli\src\ngtsc\core\src\compiler.js:352:27)
    at NgCompiler.analyzeSync (C:\Users\HP\Desktop\shop\shop-fwk-front-core\node_modules\@angular\compiler-cli\src\ngtsc\core\src\compiler.js:349:18)
    at NgCompiler.ensureAnalyzed (C:\Users\HP\Desktop\shop\shop-fwk-front-core\node_modules\@angular\compiler-cli\src\ngtsc\core\src\compiler.js:321:22)
    at NgCompiler.getDiagnostics (C:\Users\HP\Desktop\shop\shop-fwk-front-core\node_modules\@angular\compiler-cli\src\ngtsc\core\src\compiler.js:131:40)
    at NgtscProgram.getNgSemanticDiagnostics (C:\Users\HP\Desktop\shop\shop-fwk-front-core\node_modules\@angular\compiler-cli\src\ngtsc\program.js:132:45)
    at checkDiagnostics (C:\Users\HP\Desktop\shop\shop-fwk-front-core\node_modules\@ngtools\webpack\src\diagnostics.js:46:27)

**Steps to reproduce and a minimal demo**
Errors show after intstall the package and import in the app.module

  - OS: 
  - Angular Version: "^9.1.11",
  - Typescript version: "3.8.3"
  - npm version: 6.14.1
  - Node Version: v14.8.0

**Comment by pookdeveloper** [comment]
The error is because the import is incorrect:
Error:
`import { CustomFormsModule } from 'ngx-custom-validators/src/app/custom-forms.module';`
Works:
`import { CustomFormsModule } from 'ngx-custom-validators';
`
